// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: com/github/opendglab/app.proto

package opendglab

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DGEvent int32

const (
	DGEvent_EVENTUNSET   DGEvent = 0  // unset
	DGEvent_CONNECT      DGEvent = 1  // connect (send body DGConnect / receive body DGConnect)
	DGEvent_GETDEVICE    DGEvent = 2  // get devices (no send body / receive body DGDeviceList)
	DGEvent_LOCKDEVICE   DGEvent = 3  // lock device into remote mode (send body DGDeviceID / receive body DGDevice)
	DGEvent_UNLOCKDEVICE DGEvent = 4  // unlock device remote mode (send body DGDeviceID / receive body DGDevice)
	DGEvent_GETSTRENGTH  DGEvent = 5  // get strength (send body DGDeviceID / receive body DGDeviceID, DGDeviceStrength)
	DGEvent_SETSTRENGTH  DGEvent = 6  // set strength (send body DGDeviceID, DGStrength / no response)
	DGEvent_GETWAVELIST  DGEvent = 7  // get wave list (no send body / receive body DGWaveList)
	DGEvent_GETWAVE      DGEvent = 8  // get wave name (send body DGDeviceID / receive body DGDeviceID, DGWave)
	DGEvent_SETWAVE      DGEvent = 9  // set wave (send body DGDeviceID, DGWave / no response)
	DGEvent_CUSTOMWAVE   DGEvent = 10 // send custom wave (send body DGDeviceID, DGCustomWave / no response)
	DGEvent_CLEARCUSTOM  DGEvent = 11 // clear custom wave (send body DGDeviceID / no response)
	DGEvent_DEVICERESET  DGEvent = 12 // device state has been reset (no send / receive body DGDeviceID)
	DGEvent_CANTDOTHIS   DGEvent = 13 // response for an action that cannot be performed (no send / receive body DGError, optional DGDeviceID)
	DGEvent_PING         DGEvent = 14 // Ping
)

// Enum value maps for DGEvent.
var (
	DGEvent_name = map[int32]string{
		0:  "EVENTUNSET",
		1:  "CONNECT",
		2:  "GETDEVICE",
		3:  "LOCKDEVICE",
		4:  "UNLOCKDEVICE",
		5:  "GETSTRENGTH",
		6:  "SETSTRENGTH",
		7:  "GETWAVELIST",
		8:  "GETWAVE",
		9:  "SETWAVE",
		10: "CUSTOMWAVE",
		11: "CLEARCUSTOM",
		12: "DEVICERESET",
		13: "CANTDOTHIS",
		14: "PING",
	}
	DGEvent_value = map[string]int32{
		"EVENTUNSET":   0,
		"CONNECT":      1,
		"GETDEVICE":    2,
		"LOCKDEVICE":   3,
		"UNLOCKDEVICE": 4,
		"GETSTRENGTH":  5,
		"SETSTRENGTH":  6,
		"GETWAVELIST":  7,
		"GETWAVE":      8,
		"SETWAVE":      9,
		"CUSTOMWAVE":   10,
		"CLEARCUSTOM":  11,
		"DEVICERESET":  12,
		"CANTDOTHIS":   13,
		"PING":         14,
	}
)

func (x DGEvent) Enum() *DGEvent {
	p := new(DGEvent)
	*p = x
	return p
}

func (x DGEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DGEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_com_github_opendglab_app_proto_enumTypes[0].Descriptor()
}

func (DGEvent) Type() protoreflect.EnumType {
	return &file_com_github_opendglab_app_proto_enumTypes[0]
}

func (x DGEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DGEvent.Descriptor instead.
func (DGEvent) EnumDescriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{0}
}

// Error response
type DGError int32

const (
	DGError_ERRORUNSET         DGError = 0 // unset
	DGError_UNKNOWN            DGError = 1 // unknown error
	DGError_UNAUTHED           DGError = 2 // unauthenticated operation
	DGError_DEVICENOTLOCK      DGError = 3 // device is not locked into remote mode
	DGError_DEVICENOTLOCKBYYOU DGError = 4 // this device was not locked by you
	DGError_DEVICEOFFLINE      DGError = 5 // device is offline
)

// Enum value maps for DGError.
var (
	DGError_name = map[int32]string{
		0: "ERRORUNSET",
		1: "UNKNOWN",
		2: "UNAUTHED",
		3: "DEVICENOTLOCK",
		4: "DEVICENOTLOCKBYYOU",
		5: "DEVICEOFFLINE",
	}
	DGError_value = map[string]int32{
		"ERRORUNSET":         0,
		"UNKNOWN":            1,
		"UNAUTHED":           2,
		"DEVICENOTLOCK":      3,
		"DEVICENOTLOCKBYYOU": 4,
		"DEVICEOFFLINE":      5,
	}
)

func (x DGError) Enum() *DGError {
	p := new(DGError)
	*p = x
	return p
}

func (x DGError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DGError) Descriptor() protoreflect.EnumDescriptor {
	return file_com_github_opendglab_app_proto_enumTypes[1].Descriptor()
}

func (DGError) Type() protoreflect.EnumType {
	return &file_com_github_opendglab_app_proto_enumTypes[1]
}

func (x DGError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DGError.Descriptor instead.
func (DGError) EnumDescriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{1}
}

// Device channel
type DGDeviceChannel int32

const (
	DGDeviceChannel_UNSET     DGDeviceChannel = 0 // unset
	DGDeviceChannel_CHANNEL_A DGDeviceChannel = 1 // channel A
	DGDeviceChannel_CHANNEL_B DGDeviceChannel = 2 // channel B
)

// Enum value maps for DGDeviceChannel.
var (
	DGDeviceChannel_name = map[int32]string{
		0: "UNSET",
		1: "CHANNEL_A",
		2: "CHANNEL_B",
	}
	DGDeviceChannel_value = map[string]int32{
		"UNSET":     0,
		"CHANNEL_A": 1,
		"CHANNEL_B": 2,
	}
)

func (x DGDeviceChannel) Enum() *DGDeviceChannel {
	p := new(DGDeviceChannel)
	*p = x
	return p
}

func (x DGDeviceChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DGDeviceChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_com_github_opendglab_app_proto_enumTypes[2].Descriptor()
}

func (DGDeviceChannel) Type() protoreflect.EnumType {
	return &file_com_github_opendglab_app_proto_enumTypes[2]
}

func (x DGDeviceChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DGDeviceChannel.Descriptor instead.
func (DGDeviceChannel) EnumDescriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{2}
}

// Client -> OpenDGLab controller
type DGRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Version       int32                     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                               // protocol version, currently 1
	Event         DGEvent                   `protobuf:"varint,2,opt,name=event,proto3,enum=com.github.opendglab.DGEvent" json:"event,omitempty"` // operation
	Connect       *DGRequest_DGConnect      `protobuf:"bytes,3,opt,name=connect,proto3" json:"connect,omitempty"`                                // connect parameters
	Device        *DGRequest_DGDeviceID     `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`                                  // device ID
	Strength      *DGRequest_DGStrength     `protobuf:"bytes,5,opt,name=strength,proto3" json:"strength,omitempty"`                              // strength
	Wave          *DGRequest_DGWave         `protobuf:"bytes,6,opt,name=wave,proto3" json:"wave,omitempty"`                                      // wave
	CustomWave    []*DGRequest_DGCustomWave `protobuf:"bytes,7,rep,name=customWave,proto3" json:"customWave,omitempty"`                          // custom wave
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRequest) Reset() {
	*x = DGRequest{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRequest) ProtoMessage() {}

func (x *DGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRequest.ProtoReflect.Descriptor instead.
func (*DGRequest) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{0}
}

func (x *DGRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DGRequest) GetEvent() DGEvent {
	if x != nil {
		return x.Event
	}
	return DGEvent_EVENTUNSET
}

func (x *DGRequest) GetConnect() *DGRequest_DGConnect {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *DGRequest) GetDevice() *DGRequest_DGDeviceID {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DGRequest) GetStrength() *DGRequest_DGStrength {
	if x != nil {
		return x.Strength
	}
	return nil
}

func (x *DGRequest) GetWave() *DGRequest_DGWave {
	if x != nil {
		return x.Wave
	}
	return nil
}

func (x *DGRequest) GetCustomWave() []*DGRequest_DGCustomWave {
	if x != nil {
		return x.CustomWave
	}
	return nil
}

// OpenDGLab controller -> client
type DGResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Version       int32                        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                // protocol version, currently 1
	Event         DGEvent                      `protobuf:"varint,2,opt,name=event,proto3,enum=com.github.opendglab.DGEvent" json:"event,omitempty"`  // operation
	Connect       *DGResponse_DGConnect        `protobuf:"bytes,3,opt,name=connect,proto3" json:"connect,omitempty"`                                 // connect response
	DeviceList    *DGResponse_DGDeviceList     `protobuf:"bytes,4,opt,name=deviceList,proto3" json:"deviceList,omitempty"`                           // device list
	DeviceId      *DGResponse_DGDeviceID       `protobuf:"bytes,5,opt,name=deviceId,proto3" json:"deviceId,omitempty"`                               // device ID
	Device        *DGResponse_DGDevice         `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`                                   // single device
	Strength      *DGResponse_DGDeviceStrength `protobuf:"bytes,7,opt,name=strength,proto3" json:"strength,omitempty"`                               // strength
	WaveList      *DGResponse_DGWaveList       `protobuf:"bytes,8,opt,name=waveList,proto3" json:"waveList,omitempty"`                               // wave list
	WaveName      *DGResponse_DGWave           `protobuf:"bytes,9,opt,name=waveName,proto3" json:"waveName,omitempty"`                               // wave name
	Error         DGError                      `protobuf:"varint,10,opt,name=error,proto3,enum=com.github.opendglab.DGError" json:"error,omitempty"` // response error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGResponse) Reset() {
	*x = DGResponse{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGResponse) ProtoMessage() {}

func (x *DGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGResponse.ProtoReflect.Descriptor instead.
func (*DGResponse) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{1}
}

func (x *DGResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DGResponse) GetEvent() DGEvent {
	if x != nil {
		return x.Event
	}
	return DGEvent_EVENTUNSET
}

func (x *DGResponse) GetConnect() *DGResponse_DGConnect {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *DGResponse) GetDeviceList() *DGResponse_DGDeviceList {
	if x != nil {
		return x.DeviceList
	}
	return nil
}

func (x *DGResponse) GetDeviceId() *DGResponse_DGDeviceID {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *DGResponse) GetDevice() *DGResponse_DGDevice {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DGResponse) GetStrength() *DGResponse_DGDeviceStrength {
	if x != nil {
		return x.Strength
	}
	return nil
}

func (x *DGResponse) GetWaveList() *DGResponse_DGWaveList {
	if x != nil {
		return x.WaveList
	}
	return nil
}

func (x *DGResponse) GetWaveName() *DGResponse_DGWave {
	if x != nil {
		return x.WaveName
	}
	return nil
}

func (x *DGResponse) GetError() DGError {
	if x != nil {
		return x.Error
	}
	return DGError_ERRORUNSET
}

// Connect
type DGRequest_DGConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"` // application name
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`       // application ID
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`     // pre-authorized key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRequest_DGConnect) Reset() {
	*x = DGRequest_DGConnect{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRequest_DGConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRequest_DGConnect) ProtoMessage() {}

func (x *DGRequest_DGConnect) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRequest_DGConnect.ProtoReflect.Descriptor instead.
func (*DGRequest_DGConnect) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DGRequest_DGConnect) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DGRequest_DGConnect) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DGRequest_DGConnect) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Device ID
type DGRequest_DGDeviceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`                                                      // device ID
	DeviceChannel DGDeviceChannel        `protobuf:"varint,2,opt,name=deviceChannel,proto3,enum=com.github.opendglab.DGDeviceChannel" json:"deviceChannel,omitempty"` // device channel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRequest_DGDeviceID) Reset() {
	*x = DGRequest_DGDeviceID{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRequest_DGDeviceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRequest_DGDeviceID) ProtoMessage() {}

func (x *DGRequest_DGDeviceID) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRequest_DGDeviceID.ProtoReflect.Descriptor instead.
func (*DGRequest_DGDeviceID) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DGRequest_DGDeviceID) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DGRequest_DGDeviceID) GetDeviceChannel() DGDeviceChannel {
	if x != nil {
		return x.DeviceChannel
	}
	return DGDeviceChannel_UNSET
}

// Strength setting. Each field is optional: omit a channel to leave its
// current value unchanged. Setting both keeps the original behavior.
//
// Per-channel percent fields (strengthAPercent / strengthBPercent) specify
// the strength as a percentage of the channel's soft limit (0 = 0,
// 100 = soft limit). Values above 100 are clamped to 100; negative values
// are clamped to 0. If both the absolute and percent field of the same
// channel are set, the percent field takes precedence.
type DGRequest_DGStrength struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StrengthA        *int32                 `protobuf:"varint,1,opt,name=strengthA,proto3,oneof" json:"strengthA,omitempty"`               // channel A (absolute, 0..200)
	StrengthB        *int32                 `protobuf:"varint,2,opt,name=strengthB,proto3,oneof" json:"strengthB,omitempty"`               // channel B (absolute, 0..200)
	StrengthAPercent *int32                 `protobuf:"varint,3,opt,name=strengthAPercent,proto3,oneof" json:"strengthAPercent,omitempty"` // channel A (percent of soft limit, 0..100)
	StrengthBPercent *int32                 `protobuf:"varint,4,opt,name=strengthBPercent,proto3,oneof" json:"strengthBPercent,omitempty"` // channel B (percent of soft limit, 0..100)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DGRequest_DGStrength) Reset() {
	*x = DGRequest_DGStrength{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRequest_DGStrength) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRequest_DGStrength) ProtoMessage() {}

func (x *DGRequest_DGStrength) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRequest_DGStrength.ProtoReflect.Descriptor instead.
func (*DGRequest_DGStrength) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{0, 2}
}

func (x *DGRequest_DGStrength) GetStrengthA() int32 {
	if x != nil && x.StrengthA != nil {
		return *x.StrengthA
	}
	return 0
}

func (x *DGRequest_DGStrength) GetStrengthB() int32 {
	if x != nil && x.StrengthB != nil {
		return *x.StrengthB
	}
	return 0
}

func (x *DGRequest_DGStrength) GetStrengthAPercent() int32 {
	if x != nil && x.StrengthAPercent != nil {
		return *x.StrengthAPercent
	}
	return 0
}

func (x *DGRequest_DGStrength) GetStrengthBPercent() int32 {
	if x != nil && x.StrengthBPercent != nil {
		return *x.StrengthBPercent
	}
	return 0
}

// Wave
type DGRequest_DGWave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaveName      string                 `protobuf:"bytes,1,opt,name=waveName,proto3" json:"waveName,omitempty"` // wave name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRequest_DGWave) Reset() {
	*x = DGRequest_DGWave{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRequest_DGWave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRequest_DGWave) ProtoMessage() {}

func (x *DGRequest_DGWave) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRequest_DGWave.ProtoReflect.Descriptor instead.
func (*DGRequest_DGWave) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{0, 3}
}

func (x *DGRequest_DGWave) GetWaveName() string {
	if x != nil {
		return x.WaveName
	}
	return ""
}

// Custom wave
type DGRequest_DGCustomWave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"` // wave data, must be 3 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRequest_DGCustomWave) Reset() {
	*x = DGRequest_DGCustomWave{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRequest_DGCustomWave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRequest_DGCustomWave) ProtoMessage() {}

func (x *DGRequest_DGCustomWave) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRequest_DGCustomWave.ProtoReflect.Descriptor instead.
func (*DGRequest_DGCustomWave) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{0, 4}
}

func (x *DGRequest_DGCustomWave) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// Connect
type DGResponse_DGConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // authorization key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGResponse_DGConnect) Reset() {
	*x = DGResponse_DGConnect{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGResponse_DGConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGResponse_DGConnect) ProtoMessage() {}

func (x *DGResponse_DGConnect) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGResponse_DGConnect.ProtoReflect.Descriptor instead.
func (*DGResponse_DGConnect) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DGResponse_DGConnect) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Device list
type DGResponse_DGDeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DGResponse_DGDevice `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"` // device list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGResponse_DGDeviceList) Reset() {
	*x = DGResponse_DGDeviceList{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGResponse_DGDeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGResponse_DGDeviceList) ProtoMessage() {}

func (x *DGResponse_DGDeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGResponse_DGDeviceList.ProtoReflect.Descriptor instead.
func (*DGResponse_DGDeviceList) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{1, 1}
}

func (x *DGResponse_DGDeviceList) GetDevices() []*DGResponse_DGDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

// Device
type DGResponse_DGDevice struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                              // device ID
	IsLockedByRemote bool                   `protobuf:"varint,2,opt,name=isLockedByRemote,proto3" json:"isLockedByRemote,omitempty"` // whether it is in remote locked mode
	IsLockedByMe     bool                   `protobuf:"varint,3,opt,name=isLockedByMe,proto3" json:"isLockedByMe,omitempty"`         // whether it was locked by this software
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DGResponse_DGDevice) Reset() {
	*x = DGResponse_DGDevice{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGResponse_DGDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGResponse_DGDevice) ProtoMessage() {}

func (x *DGResponse_DGDevice) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGResponse_DGDevice.ProtoReflect.Descriptor instead.
func (*DGResponse_DGDevice) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{1, 2}
}

func (x *DGResponse_DGDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DGResponse_DGDevice) GetIsLockedByRemote() bool {
	if x != nil {
		return x.IsLockedByRemote
	}
	return false
}

func (x *DGResponse_DGDevice) GetIsLockedByMe() bool {
	if x != nil {
		return x.IsLockedByMe
	}
	return false
}

// Device ID
type DGResponse_DGDeviceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`                                                      // device ID
	DeviceChannel DGDeviceChannel        `protobuf:"varint,2,opt,name=deviceChannel,proto3,enum=com.github.opendglab.DGDeviceChannel" json:"deviceChannel,omitempty"` // device channel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGResponse_DGDeviceID) Reset() {
	*x = DGResponse_DGDeviceID{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGResponse_DGDeviceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGResponse_DGDeviceID) ProtoMessage() {}

func (x *DGResponse_DGDeviceID) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGResponse_DGDeviceID.ProtoReflect.Descriptor instead.
func (*DGResponse_DGDeviceID) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{1, 3}
}

func (x *DGResponse_DGDeviceID) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DGResponse_DGDeviceID) GetDeviceChannel() DGDeviceChannel {
	if x != nil {
		return x.DeviceChannel
	}
	return DGDeviceChannel_UNSET
}

// Strength
type DGResponse_DGDeviceStrength struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrengthA     int32                  `protobuf:"varint,1,opt,name=strengthA,proto3" json:"strengthA,omitempty"` // channel A
	StrengthB     int32                  `protobuf:"varint,2,opt,name=strengthB,proto3" json:"strengthB,omitempty"` // channel B
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGResponse_DGDeviceStrength) Reset() {
	*x = DGResponse_DGDeviceStrength{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGResponse_DGDeviceStrength) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGResponse_DGDeviceStrength) ProtoMessage() {}

func (x *DGResponse_DGDeviceStrength) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGResponse_DGDeviceStrength.ProtoReflect.Descriptor instead.
func (*DGResponse_DGDeviceStrength) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{1, 4}
}

func (x *DGResponse_DGDeviceStrength) GetStrengthA() int32 {
	if x != nil {
		return x.StrengthA
	}
	return 0
}

func (x *DGResponse_DGDeviceStrength) GetStrengthB() int32 {
	if x != nil {
		return x.StrengthB
	}
	return 0
}

// Wave list
type DGResponse_DGWaveList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wave          []string               `protobuf:"bytes,1,rep,name=wave,proto3" json:"wave,omitempty"` // list of wave names
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGResponse_DGWaveList) Reset() {
	*x = DGResponse_DGWaveList{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGResponse_DGWaveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGResponse_DGWaveList) ProtoMessage() {}

func (x *DGResponse_DGWaveList) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGResponse_DGWaveList.ProtoReflect.Descriptor instead.
func (*DGResponse_DGWaveList) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{1, 5}
}

func (x *DGResponse_DGWaveList) GetWave() []string {
	if x != nil {
		return x.Wave
	}
	return nil
}

// Wave
type DGResponse_DGWave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wave          string                 `protobuf:"bytes,1,opt,name=wave,proto3" json:"wave,omitempty"` // wave name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGResponse_DGWave) Reset() {
	*x = DGResponse_DGWave{}
	mi := &file_com_github_opendglab_app_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGResponse_DGWave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGResponse_DGWave) ProtoMessage() {}

func (x *DGResponse_DGWave) ProtoReflect() protoreflect.Message {
	mi := &file_com_github_opendglab_app_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGResponse_DGWave.ProtoReflect.Descriptor instead.
func (*DGResponse_DGWave) Descriptor() ([]byte, []int) {
	return file_com_github_opendglab_app_proto_rawDescGZIP(), []int{1, 6}
}

func (x *DGResponse_DGWave) GetWave() string {
	if x != nil {
		return x.Wave
	}
	return ""
}

var File_com_github_opendglab_app_proto protoreflect.FileDescriptor

const file_com_github_opendglab_app_proto_rawDesc = "" +
	"\n" +
	"\x1ecom/github/opendglab/app.proto\x12\x14com.github.opendglab\"\xc6\a\n" +
	"\tDGRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x123\n" +
	"\x05event\x18\x02 \x01(\x0e2\x1d.com.github.opendglab.DGEventR\x05event\x12C\n" +
	"\aconnect\x18\x03 \x01(\v2).com.github.opendglab.DGRequest.DGConnectR\aconnect\x12B\n" +
	"\x06device\x18\x04 \x01(\v2*.com.github.opendglab.DGRequest.DGDeviceIDR\x06device\x12F\n" +
	"\bstrength\x18\x05 \x01(\v2*.com.github.opendglab.DGRequest.DGStrengthR\bstrength\x12:\n" +
	"\x04wave\x18\x06 \x01(\v2&.com.github.opendglab.DGRequest.DGWaveR\x04wave\x12L\n" +
	"\n" +
	"customWave\x18\a \x03(\v2,.com.github.opendglab.DGRequest.DGCustomWaveR\n" +
	"customWave\x1aO\n" +
	"\tDGConnect\x12\x18\n" +
	"\aappName\x18\x01 \x01(\tR\aappName\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x1au\n" +
	"\n" +
	"DGDeviceID\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x01(\tR\bdeviceId\x12K\n" +
	"\rdeviceChannel\x18\x02 \x01(\x0e2%.com.github.opendglab.DGDeviceChannelR\rdeviceChannel\x1a\xfa\x01\n" +
	"\n" +
	"DGStrength\x12!\n" +
	"\tstrengthA\x18\x01 \x01(\x05H\x00R\tstrengthA\x88\x01\x01\x12!\n" +
	"\tstrengthB\x18\x02 \x01(\x05H\x01R\tstrengthB\x88\x01\x01\x12/\n" +
	"\x10strengthAPercent\x18\x03 \x01(\x05H\x02R\x10strengthAPercent\x88\x01\x01\x12/\n" +
	"\x10strengthBPercent\x18\x04 \x01(\x05H\x03R\x10strengthBPercent\x88\x01\x01B\f\n" +
	"\n" +
	"_strengthAB\f\n" +
	"\n" +
	"_strengthBB\x13\n" +
	"\x11_strengthAPercentB\x13\n" +
	"\x11_strengthBPercent\x1a$\n" +
	"\x06DGWave\x12\x1a\n" +
	"\bwaveName\x18\x01 \x01(\tR\bwaveName\x1a$\n" +
	"\fDGCustomWave\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"\xf9\b\n" +
	"\n" +
	"DGResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x123\n" +
	"\x05event\x18\x02 \x01(\x0e2\x1d.com.github.opendglab.DGEventR\x05event\x12D\n" +
	"\aconnect\x18\x03 \x01(\v2*.com.github.opendglab.DGResponse.DGConnectR\aconnect\x12M\n" +
	"\n" +
	"deviceList\x18\x04 \x01(\v2-.com.github.opendglab.DGResponse.DGDeviceListR\n" +
	"deviceList\x12G\n" +
	"\bdeviceId\x18\x05 \x01(\v2+.com.github.opendglab.DGResponse.DGDeviceIDR\bdeviceId\x12A\n" +
	"\x06device\x18\x06 \x01(\v2).com.github.opendglab.DGResponse.DGDeviceR\x06device\x12M\n" +
	"\bstrength\x18\a \x01(\v21.com.github.opendglab.DGResponse.DGDeviceStrengthR\bstrength\x12G\n" +
	"\bwaveList\x18\b \x01(\v2+.com.github.opendglab.DGResponse.DGWaveListR\bwaveList\x12C\n" +
	"\bwaveName\x18\t \x01(\v2'.com.github.opendglab.DGResponse.DGWaveR\bwaveName\x123\n" +
	"\x05error\x18\n" +
	" \x01(\x0e2\x1d.com.github.opendglab.DGErrorR\x05error\x1a!\n" +
	"\tDGConnect\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x1aS\n" +
	"\fDGDeviceList\x12C\n" +
	"\adevices\x18\x01 \x03(\v2).com.github.opendglab.DGResponse.DGDeviceR\adevices\x1aj\n" +
	"\bDGDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x10isLockedByRemote\x18\x02 \x01(\bR\x10isLockedByRemote\x12\"\n" +
	"\fisLockedByMe\x18\x03 \x01(\bR\fisLockedByMe\x1au\n" +
	"\n" +
	"DGDeviceID\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x01(\tR\bdeviceId\x12K\n" +
	"\rdeviceChannel\x18\x02 \x01(\x0e2%.com.github.opendglab.DGDeviceChannelR\rdeviceChannel\x1aN\n" +
	"\x10DGDeviceStrength\x12\x1c\n" +
	"\tstrengthA\x18\x01 \x01(\x05R\tstrengthA\x12\x1c\n" +
	"\tstrengthB\x18\x02 \x01(\x05R\tstrengthB\x1a \n" +
	"\n" +
	"DGWaveList\x12\x12\n" +
	"\x04wave\x18\x01 \x03(\tR\x04wave\x1a\x1c\n" +
	"\x06DGWave\x12\x12\n" +
	"\x04wave\x18\x01 \x01(\tR\x04wave*\xf0\x01\n" +
	"\aDGEvent\x12\x0e\n" +
	"\n" +
	"EVENTUNSET\x10\x00\x12\v\n" +
	"\aCONNECT\x10\x01\x12\r\n" +
	"\tGETDEVICE\x10\x02\x12\x0e\n" +
	"\n" +
	"LOCKDEVICE\x10\x03\x12\x10\n" +
	"\fUNLOCKDEVICE\x10\x04\x12\x0f\n" +
	"\vGETSTRENGTH\x10\x05\x12\x0f\n" +
	"\vSETSTRENGTH\x10\x06\x12\x0f\n" +
	"\vGETWAVELIST\x10\a\x12\v\n" +
	"\aGETWAVE\x10\b\x12\v\n" +
	"\aSETWAVE\x10\t\x12\x0e\n" +
	"\n" +
	"CUSTOMWAVE\x10\n" +
	"\x12\x0f\n" +
	"\vCLEARCUSTOM\x10\v\x12\x0f\n" +
	"\vDEVICERESET\x10\f\x12\x0e\n" +
	"\n" +
	"CANTDOTHIS\x10\r\x12\b\n" +
	"\x04PING\x10\x0e*r\n" +
	"\aDGError\x12\x0e\n" +
	"\n" +
	"ERRORUNSET\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\f\n" +
	"\bUNAUTHED\x10\x02\x12\x11\n" +
	"\rDEVICENOTLOCK\x10\x03\x12\x16\n" +
	"\x12DEVICENOTLOCKBYYOU\x10\x04\x12\x11\n" +
	"\rDEVICEOFFLINE\x10\x05*:\n" +
	"\x0fDGDeviceChannel\x12\t\n" +
	"\x05UNSET\x10\x00\x12\r\n" +
	"\tCHANNEL_A\x10\x01\x12\r\n" +
	"\tCHANNEL_B\x10\x022\xaf\x01\n" +
	"\x10OpenDGLabService\x12I\n" +
	"\x04Send\x12\x1f.com.github.opendglab.DGRequest\x1a .com.github.opendglab.DGResponse\x12P\n" +
	"\tSubscribe\x12\x1f.com.github.opendglab.DGRequest\x1a .com.github.opendglab.DGResponse0\x01B\xe1\x01\n" +
	"\x18com.com.github.opendglabB\bAppProtoP\x01ZIgithub.com/hantabaru1014/dgl-desktop-hub/internal/pb/com/github/opendglab\xa2\x02\x03CGO\xaa\x02\x14Com.Github.Opendglab\xca\x02\x14Com\\Github\\Opendglab\xe2\x02 Com\\Github\\Opendglab\\GPBMetadata\xea\x02\x16Com::Github::Opendglabb\x06proto3"

var (
	file_com_github_opendglab_app_proto_rawDescOnce sync.Once
	file_com_github_opendglab_app_proto_rawDescData []byte
)

func file_com_github_opendglab_app_proto_rawDescGZIP() []byte {
	file_com_github_opendglab_app_proto_rawDescOnce.Do(func() {
		file_com_github_opendglab_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_github_opendglab_app_proto_rawDesc), len(file_com_github_opendglab_app_proto_rawDesc)))
	})
	return file_com_github_opendglab_app_proto_rawDescData
}

var file_com_github_opendglab_app_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_com_github_opendglab_app_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_com_github_opendglab_app_proto_goTypes = []any{
	(DGEvent)(0),                        // 0: com.github.opendglab.DGEvent
	(DGError)(0),                        // 1: com.github.opendglab.DGError
	(DGDeviceChannel)(0),                // 2: com.github.opendglab.DGDeviceChannel
	(*DGRequest)(nil),                   // 3: com.github.opendglab.DGRequest
	(*DGResponse)(nil),                  // 4: com.github.opendglab.DGResponse
	(*DGRequest_DGConnect)(nil),         // 5: com.github.opendglab.DGRequest.DGConnect
	(*DGRequest_DGDeviceID)(nil),        // 6: com.github.opendglab.DGRequest.DGDeviceID
	(*DGRequest_DGStrength)(nil),        // 7: com.github.opendglab.DGRequest.DGStrength
	(*DGRequest_DGWave)(nil),            // 8: com.github.opendglab.DGRequest.DGWave
	(*DGRequest_DGCustomWave)(nil),      // 9: com.github.opendglab.DGRequest.DGCustomWave
	(*DGResponse_DGConnect)(nil),        // 10: com.github.opendglab.DGResponse.DGConnect
	(*DGResponse_DGDeviceList)(nil),     // 11: com.github.opendglab.DGResponse.DGDeviceList
	(*DGResponse_DGDevice)(nil),         // 12: com.github.opendglab.DGResponse.DGDevice
	(*DGResponse_DGDeviceID)(nil),       // 13: com.github.opendglab.DGResponse.DGDeviceID
	(*DGResponse_DGDeviceStrength)(nil), // 14: com.github.opendglab.DGResponse.DGDeviceStrength
	(*DGResponse_DGWaveList)(nil),       // 15: com.github.opendglab.DGResponse.DGWaveList
	(*DGResponse_DGWave)(nil),           // 16: com.github.opendglab.DGResponse.DGWave
}
var file_com_github_opendglab_app_proto_depIdxs = []int32{
	0,  // 0: com.github.opendglab.DGRequest.event:type_name -> com.github.opendglab.DGEvent
	5,  // 1: com.github.opendglab.DGRequest.connect:type_name -> com.github.opendglab.DGRequest.DGConnect
	6,  // 2: com.github.opendglab.DGRequest.device:type_name -> com.github.opendglab.DGRequest.DGDeviceID
	7,  // 3: com.github.opendglab.DGRequest.strength:type_name -> com.github.opendglab.DGRequest.DGStrength
	8,  // 4: com.github.opendglab.DGRequest.wave:type_name -> com.github.opendglab.DGRequest.DGWave
	9,  // 5: com.github.opendglab.DGRequest.customWave:type_name -> com.github.opendglab.DGRequest.DGCustomWave
	0,  // 6: com.github.opendglab.DGResponse.event:type_name -> com.github.opendglab.DGEvent
	10, // 7: com.github.opendglab.DGResponse.connect:type_name -> com.github.opendglab.DGResponse.DGConnect
	11, // 8: com.github.opendglab.DGResponse.deviceList:type_name -> com.github.opendglab.DGResponse.DGDeviceList
	13, // 9: com.github.opendglab.DGResponse.deviceId:type_name -> com.github.opendglab.DGResponse.DGDeviceID
	12, // 10: com.github.opendglab.DGResponse.device:type_name -> com.github.opendglab.DGResponse.DGDevice
	14, // 11: com.github.opendglab.DGResponse.strength:type_name -> com.github.opendglab.DGResponse.DGDeviceStrength
	15, // 12: com.github.opendglab.DGResponse.waveList:type_name -> com.github.opendglab.DGResponse.DGWaveList
	16, // 13: com.github.opendglab.DGResponse.waveName:type_name -> com.github.opendglab.DGResponse.DGWave
	1,  // 14: com.github.opendglab.DGResponse.error:type_name -> com.github.opendglab.DGError
	2,  // 15: com.github.opendglab.DGRequest.DGDeviceID.deviceChannel:type_name -> com.github.opendglab.DGDeviceChannel
	12, // 16: com.github.opendglab.DGResponse.DGDeviceList.devices:type_name -> com.github.opendglab.DGResponse.DGDevice
	2,  // 17: com.github.opendglab.DGResponse.DGDeviceID.deviceChannel:type_name -> com.github.opendglab.DGDeviceChannel
	3,  // 18: com.github.opendglab.OpenDGLabService.Send:input_type -> com.github.opendglab.DGRequest
	3,  // 19: com.github.opendglab.OpenDGLabService.Subscribe:input_type -> com.github.opendglab.DGRequest
	4,  // 20: com.github.opendglab.OpenDGLabService.Send:output_type -> com.github.opendglab.DGResponse
	4,  // 21: com.github.opendglab.OpenDGLabService.Subscribe:output_type -> com.github.opendglab.DGResponse
	20, // [20:22] is the sub-list for method output_type
	18, // [18:20] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_com_github_opendglab_app_proto_init() }
func file_com_github_opendglab_app_proto_init() {
	if File_com_github_opendglab_app_proto != nil {
		return
	}
	file_com_github_opendglab_app_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_github_opendglab_app_proto_rawDesc), len(file_com_github_opendglab_app_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_github_opendglab_app_proto_goTypes,
		DependencyIndexes: file_com_github_opendglab_app_proto_depIdxs,
		EnumInfos:         file_com_github_opendglab_app_proto_enumTypes,
		MessageInfos:      file_com_github_opendglab_app_proto_msgTypes,
	}.Build()
	File_com_github_opendglab_app_proto = out.File
	file_com_github_opendglab_app_proto_goTypes = nil
	file_com_github_opendglab_app_proto_depIdxs = nil
}
