// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HubService はハブ全体をフロントエンドへ公開する Wails サービス。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddDemoDevice は疑似デバイスを追加して返す。
 */
export function AddDemoDevice(name: string): $CancellablePromise<$models.DeviceDTO> {
    return $Call.ByID(3670212994, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ApproveConnection はモーダルでの承認/拒否を反映する。
 */
export function ApproveConnection(requestID: string, approve: boolean): $CancellablePromise<void> {
    return $Call.ByID(2348918365, requestID, approve);
}

/**
 * ClearWaveform は波形を無出力にする。channel: 0=A,1=B,-1=両方。
 */
export function ClearWaveform(id: string, channel: number): $CancellablePromise<void> {
    return $Call.ByID(3065503002, id, channel);
}

/**
 * ConnectBLE はアドレスを指定して BLE Coyote へ接続し、デバイスを追加する。
 * 直前に ScanBLE を実行している必要がある。
 */
export function ConnectBLE(addr: string, name: string): $CancellablePromise<$models.DeviceDTO> {
    return $Call.ByID(2056154703, addr, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAccessMode は現在のアクセスモード (接続自動許可) を返す。
 */
export function GetAccessMode(): $CancellablePromise<$models.AccessModeDTO> {
    return $Call.ByID(1725393789).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAppInfo はソフトウェアの概要情報 (名称・リポジトリ URL・コミット SHA) を返す。
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfoDTO> {
    return $Call.ByID(2499129323).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetPresets は波形プリセット一覧を返す。
 */
export function GetPresets(): $CancellablePromise<$models.PresetDTO[]> {
    return $Call.ByID(1046178320).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetServerInfo はアプリ操作側の待ち受け情報を返す。
 * 表示 URL は既定で localhost (サーバは 0.0.0.0 で待ち受けるため LAN からも到達可)。
 */
export function GetServerInfo(): $CancellablePromise<$models.ServerInfoDTO> {
    return $Call.ByID(3658785163).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetSocketServerInfo は socket mode サーバの現在状態を返す。
 */
export function GetSocketServerInfo(): $CancellablePromise<$models.SocketServerDTO> {
    return $Call.ByID(1649052066).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListApps は接続中アプリ一覧を返す。
 */
export function ListApps(): $CancellablePromise<$models.AppDTO[]> {
    return $Call.ByID(124334256).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListDevices は全デバイスを返す。
 */
export function ListDevices(): $CancellablePromise<$models.DeviceDTO[]> {
    return $Call.ByID(2285248163).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * RemoveDevice はデバイスを削除する。
 */
export function RemoveDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(955682306, id);
}

/**
 * ScanBLE は seconds 秒間 BLE をスキャンし、Coyote v3 候補を返す。
 */
export function ScanBLE(seconds: number): $CancellablePromise<$models.ScanResultDTO[]> {
    return $Call.ByID(649496214, seconds).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SetAppServerPort はアプリ操作側ポートを変更し永続化、サーバを再起動する。
 */
export function SetAppServerPort(port: number): $CancellablePromise<$models.ServerInfoDTO> {
    return $Call.ByID(2053346435, port).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SetAutoApprove は接続自動許可を設定する。
 */
export function SetAutoApprove(autoApprove: boolean): $CancellablePromise<void> {
    return $Call.ByID(4268545532, autoApprove);
}

/**
 * SetDeviceExclusive はデバイスの排他モードを設定し永続化する。
 */
export function SetDeviceExclusive(id: string, exclusive: boolean): $CancellablePromise<void> {
    return $Call.ByID(722386442, id, exclusive);
}

/**
 * SetSocketHost は socket QR に使うホストを保存する。
 */
export function SetSocketHost(host: string): $CancellablePromise<void> {
    return $Call.ByID(2571072019, host);
}

/**
 * SetSoftLimit はチャンネル毎の強度ソフトリミットを設定し、永続化する。
 */
export function SetSoftLimit(id: string, a: number, b: number): $CancellablePromise<void> {
    return $Call.ByID(2847189051, id, a, b);
}

/**
 * SetStrength は強度を設定する。channel: 0=A,1=B。mode: 0=絶対,1=相対増,2=相対減。
 */
export function SetStrength(id: string, channel: number, mode: number, val: number): $CancellablePromise<void> {
    return $Call.ByID(1356974161, id, channel, mode, val);
}

/**
 * SetWaveformPreset はプリセット名で波形を設定する。channel: 0=A,1=B,-1=両方。
 */
export function SetWaveformPreset(id: string, channel: number, presetName: string): $CancellablePromise<void> {
    return $Call.ByID(4179757948, id, channel, presetName);
}

/**
 * StartAppServer はアプリ操作側 (OpenDGLab) サーバを永続化ポートで起動する。
 * アプリ起動時に main から呼ばれる。
 */
export function StartAppServer(): $CancellablePromise<void> {
    return $Call.ByID(1439705492);
}

/**
 * StartSocketServer は socket mode サーバを起動し、QR と待ち受け情報を返す。
 * port<=0 なら永続化された socket ポートを使う。
 */
export function StartSocketServer(port: number): $CancellablePromise<$models.SocketServerDTO> {
    return $Call.ByID(1550738394, port).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * StopSocketServer は socket mode サーバを停止する。
 */
export function StopSocketServer(): $CancellablePromise<void> {
    return $Call.ByID(1652886150);
}

// Private type creation functions
const $$createType0 = $models.DeviceDTO.createFrom;
const $$createType1 = $models.AccessModeDTO.createFrom;
const $$createType2 = $models.AppInfoDTO.createFrom;
const $$createType3 = $models.PresetDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ServerInfoDTO.createFrom;
const $$createType6 = $models.SocketServerDTO.createFrom;
const $$createType7 = $models.AppDTO.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = $models.ScanResultDTO.createFrom;
const $$createType11 = $Create.Array($$createType10);
