// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccessModeDTO はアクセスモード設定。
 */
export class AccessModeDTO {
    "autoApprove": boolean;

    /** Creates a new AccessModeDTO instance. */
    constructor($$source: Partial<AccessModeDTO> = {}) {
        if (!("autoApprove" in $$source)) {
            this["autoApprove"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessModeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessModeDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessModeDTO($$parsedSource as Partial<AccessModeDTO>);
    }
}

/**
 * AppDTO は接続中アプリ情報。
 */
export class AppDTO {
    "token": string;
    "appName": string;
    "uuid": string;

    /** Creates a new AppDTO instance. */
    constructor($$source: Partial<AppDTO> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AppDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppDTO($$parsedSource as Partial<AppDTO>);
    }
}

/**
 * ApprovalRequestDTO は接続許可要求 (UI モーダル用)。
 */
export class ApprovalRequestDTO {
    "requestId": string;
    "appName": string;
    "uuid": string;

    /** Creates a new ApprovalRequestDTO instance. */
    constructor($$source: Partial<ApprovalRequestDTO> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovalRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ApprovalRequestDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApprovalRequestDTO($$parsedSource as Partial<ApprovalRequestDTO>);
    }
}

/**
 * DeviceDTO はフロントエンドへ渡すデバイス情報 (フラット)。
 */
export class DeviceDTO {
    "id": string;
    "kind": string;
    "name": string;
    "status": string;

    /**
     * 0..100、不明なら -1
     */
    "battery": number;
    "softLimitA": number;
    "softLimitB": number;

    /**
     * 現在の強度 (ソフトリミット適用済)
     */
    "strengthA": number;
    "strengthB": number;

    /**
     * 現在の波形名 (なければ空)
     */
    "waveA": string;
    "waveB": string;

    /**
     * 排他モード (true で単一アプリのみ操作可)
     */
    "exclusive": boolean;

    /**
     * 排他モード時に専有しているアプリ名 (なければ空)
     */
    "owner": string;

    /** Creates a new DeviceDTO instance. */
    constructor($$source: Partial<DeviceDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("battery" in $$source)) {
            this["battery"] = 0;
        }
        if (!("softLimitA" in $$source)) {
            this["softLimitA"] = 0;
        }
        if (!("softLimitB" in $$source)) {
            this["softLimitB"] = 0;
        }
        if (!("strengthA" in $$source)) {
            this["strengthA"] = 0;
        }
        if (!("strengthB" in $$source)) {
            this["strengthB"] = 0;
        }
        if (!("waveA" in $$source)) {
            this["waveA"] = "";
        }
        if (!("waveB" in $$source)) {
            this["waveB"] = "";
        }
        if (!("exclusive" in $$source)) {
            this["exclusive"] = false;
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceDTO($$parsedSource as Partial<DeviceDTO>);
    }
}

/**
 * PresetDTO は波形プリセット情報。
 */
export class PresetDTO {
    "name": string;

    /** Creates a new PresetDTO instance. */
    constructor($$source: Partial<PresetDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetDTO($$parsedSource as Partial<PresetDTO>);
    }
}

/**
 * ScanResultDTO は BLE スキャンで見つかったデバイス。
 */
export class ScanResultDTO {
    "address": string;
    "name": string;
    "rssi": number;

    /** Creates a new ScanResultDTO instance. */
    constructor($$source: Partial<ScanResultDTO> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("rssi" in $$source)) {
            this["rssi"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResultDTO($$parsedSource as Partial<ScanResultDTO>);
    }
}

/**
 * ServerInfoDTO はアプリ操作側の待ち受け情報。
 */
export class ServerInfoDTO {
    /**
     * Connect/gRPC/gRPC-Web のベース URL
     */
    "connect": string;
    "port": number;
    "running": boolean;

    /** Creates a new ServerInfoDTO instance. */
    constructor($$source: Partial<ServerInfoDTO> = {}) {
        if (!("connect" in $$source)) {
            this["connect"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerInfoDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerInfoDTO($$parsedSource as Partial<ServerInfoDTO>);
    }
}

/**
 * SocketServerDTO は socket mode サーバの状態。
 */
export class SocketServerDTO {
    "running": boolean;
    "addr": string;
    "qr": string;
    "port": number;

    /**
     * QR に使うホスト (ユーザー編集可)
     */
    "host": string;

    /**
     * QR 文字列をフロントで組むための ID
     */
    "controllerId": string;

    /** Creates a new SocketServerDTO instance. */
    constructor($$source: Partial<SocketServerDTO> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("addr" in $$source)) {
            this["addr"] = "";
        }
        if (!("qr" in $$source)) {
            this["qr"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("controllerId" in $$source)) {
            this["controllerId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SocketServerDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SocketServerDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SocketServerDTO($$parsedSource as Partial<SocketServerDTO>);
    }
}
