//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "../../../../hantabaru1014/dgl-desktop-hub/internal/device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../../../../hantabaru1014/dgl-desktop-hub/services/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "app:approval": $$createType0,
        "apps:changed": $$createType2,
        "devices:changed": $$createType4,
        "graph:frame": $$createType6,
    }));
}

// Private type creation functions
const $$createType0 = services$0.ApprovalRequestDTO.createFrom;
const $$createType1 = services$0.AppDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = services$0.DeviceDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = device$0.GraphSample.createFrom;
const $$createType6 = $Create.Array($$createType5);

configure();
