// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as device$0 from "../../../../hantabaru1014/dgl-desktop-hub/internal/device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../hantabaru1014/dgl-desktop-hub/services/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app:approval": services$0.ApprovalRequestDTO;
            "apps:changed": services$0.AppDTO[];
            "devices:changed": services$0.DeviceDTO[];
            "graph:frame": device$0.GraphSample[];
        }
    }
}
