// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: com/github/opendglab/app.proto

package opendglabconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	opendglab "github.com/hantabaru1014/dgl-desktop-hub/internal/pb/com/github/opendglab"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OpenDGLabServiceName is the fully-qualified name of the OpenDGLabService service.
	OpenDGLabServiceName = "com.github.opendglab.OpenDGLabService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OpenDGLabServiceSendProcedure is the fully-qualified name of the OpenDGLabService's Send RPC.
	OpenDGLabServiceSendProcedure = "/com.github.opendglab.OpenDGLabService/Send"
	// OpenDGLabServiceSubscribeProcedure is the fully-qualified name of the OpenDGLabService's
	// Subscribe RPC.
	OpenDGLabServiceSubscribeProcedure = "/com.github.opendglab.OpenDGLabService/Subscribe"
)

// OpenDGLabServiceClient is a client for the com.github.opendglab.OpenDGLabService service.
type OpenDGLabServiceClient interface {
	Send(context.Context, *connect.Request[opendglab.DGRequest]) (*connect.Response[opendglab.DGResponse], error)
	Subscribe(context.Context, *connect.Request[opendglab.DGRequest]) (*connect.ServerStreamForClient[opendglab.DGResponse], error)
}

// NewOpenDGLabServiceClient constructs a client for the com.github.opendglab.OpenDGLabService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOpenDGLabServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OpenDGLabServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	openDGLabServiceMethods := opendglab.File_com_github_opendglab_app_proto.Services().ByName("OpenDGLabService").Methods()
	return &openDGLabServiceClient{
		send: connect.NewClient[opendglab.DGRequest, opendglab.DGResponse](
			httpClient,
			baseURL+OpenDGLabServiceSendProcedure,
			connect.WithSchema(openDGLabServiceMethods.ByName("Send")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[opendglab.DGRequest, opendglab.DGResponse](
			httpClient,
			baseURL+OpenDGLabServiceSubscribeProcedure,
			connect.WithSchema(openDGLabServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// openDGLabServiceClient implements OpenDGLabServiceClient.
type openDGLabServiceClient struct {
	send      *connect.Client[opendglab.DGRequest, opendglab.DGResponse]
	subscribe *connect.Client[opendglab.DGRequest, opendglab.DGResponse]
}

// Send calls com.github.opendglab.OpenDGLabService.Send.
func (c *openDGLabServiceClient) Send(ctx context.Context, req *connect.Request[opendglab.DGRequest]) (*connect.Response[opendglab.DGResponse], error) {
	return c.send.CallUnary(ctx, req)
}

// Subscribe calls com.github.opendglab.OpenDGLabService.Subscribe.
func (c *openDGLabServiceClient) Subscribe(ctx context.Context, req *connect.Request[opendglab.DGRequest]) (*connect.ServerStreamForClient[opendglab.DGResponse], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// OpenDGLabServiceHandler is an implementation of the com.github.opendglab.OpenDGLabService
// service.
type OpenDGLabServiceHandler interface {
	Send(context.Context, *connect.Request[opendglab.DGRequest]) (*connect.Response[opendglab.DGResponse], error)
	Subscribe(context.Context, *connect.Request[opendglab.DGRequest], *connect.ServerStream[opendglab.DGResponse]) error
}

// NewOpenDGLabServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOpenDGLabServiceHandler(svc OpenDGLabServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	openDGLabServiceMethods := opendglab.File_com_github_opendglab_app_proto.Services().ByName("OpenDGLabService").Methods()
	openDGLabServiceSendHandler := connect.NewUnaryHandler(
		OpenDGLabServiceSendProcedure,
		svc.Send,
		connect.WithSchema(openDGLabServiceMethods.ByName("Send")),
		connect.WithHandlerOptions(opts...),
	)
	openDGLabServiceSubscribeHandler := connect.NewServerStreamHandler(
		OpenDGLabServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(openDGLabServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/com.github.opendglab.OpenDGLabService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OpenDGLabServiceSendProcedure:
			openDGLabServiceSendHandler.ServeHTTP(w, r)
		case OpenDGLabServiceSubscribeProcedure:
			openDGLabServiceSubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOpenDGLabServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOpenDGLabServiceHandler struct{}

func (UnimplementedOpenDGLabServiceHandler) Send(context.Context, *connect.Request[opendglab.DGRequest]) (*connect.Response[opendglab.DGResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("com.github.opendglab.OpenDGLabService.Send is not implemented"))
}

func (UnimplementedOpenDGLabServiceHandler) Subscribe(context.Context, *connect.Request[opendglab.DGRequest], *connect.ServerStream[opendglab.DGResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("com.github.opendglab.OpenDGLabService.Subscribe is not implemented"))
}
