// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChannelOutput はグラフ描画用の 1 チャンネル分の出力値。
 */
export class ChannelOutput {
    /**
     * 現在強度 (ソフトリミット適用済) 0..limit = 白線
     */
    "strength": number;

    /**
     * 波形平均強度 0..100
     */
    "amp": number;

    /**
     * 実効出力 = clamp済強度*amp/100 = 棒
     */
    "output": number;

    /** Creates a new ChannelOutput instance. */
    constructor($$source: Partial<ChannelOutput> = {}) {
        if (!("strength" in $$source)) {
            this["strength"] = 0;
        }
        if (!("amp" in $$source)) {
            this["amp"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelOutput($$parsedSource as Partial<ChannelOutput>);
    }
}

/**
 * DeviceID はデバイスの一意な識別子。
 */
export type DeviceID = string;

/**
 * GraphSample は 1 デバイス・1 周期分のグラフサンプル。
 */
export class GraphSample {
    "deviceId": DeviceID;
    "a": ChannelOutput;
    "b": ChannelOutput;

    /** Creates a new GraphSample instance. */
    constructor($$source: Partial<GraphSample> = {}) {
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("a" in $$source)) {
            this["a"] = (new ChannelOutput());
        }
        if (!("b" in $$source)) {
            this["b"] = (new ChannelOutput());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphSample instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphSample {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("a" in $$parsedSource) {
            $$parsedSource["a"] = $$createField1_0($$parsedSource["a"]);
        }
        if ("b" in $$parsedSource) {
            $$parsedSource["b"] = $$createField2_0($$parsedSource["b"]);
        }
        return new GraphSample($$parsedSource as Partial<GraphSample>);
    }
}

// Private type creation functions
const $$createType0 = ChannelOutput.createFrom;
